include: package:solid_lints/analysis_options.yaml

plugins:
  solid_lints:

solid_lints:
  diagnostics:
    cyclomatic_complexity:
      max_complexity: 4
    number_of_parameters:
      max_parameters: 2
    function_lines_of_code:
      max_lines: 50
    avoid_non_null_assertion: true
    avoid_late_keyword: true
    avoid_global_state: true
    avoid_returning_widgets: true
    avoid_unnecessary_setstate: true
    double_literal_format: true
    avoid_unnecessary_type_assertions: true
    avoid_debug_print_in_release: true
    avoid_using_api:
      severity: info
      entries:
        - class_name: Future
          identifier: wait
          source: dart:async
          reason: "Future.wait should be avoided because it looses type safety for the results. Use a Record's `wait` method instead."
          severity: warning
