include: package:solid_lints/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - cyclomatic_complexity:
      max_complexity: 4
    - number_of_parameters:
      max_parameters: 2
    - function_lines_of_code:
      max_lines: 50
    - avoid_non_null_assertion
    - avoid_late_keyword
    - avoid_global_state
    - avoid_returning_widgets
    - avoid_unnecessary_setstate
    - double_literal_format
    - avoid_unnecessary_type_assertions
    - avoid_debug_print
    - avoid_using_api:
      severity: info
      entries:
        - class_name: Future
          identifier: wait
          source: dart:async
          reason: "Future.wait should be avoided because it looses type safety for the results. Use a Record's `wait` method instead."
          severity: warning
