analyzer:
  plugins:
    - ../../custom_lint

custom_lint:
  rules:
    - avoid_using_api:
      severity: warning
      entries:
        - source: dart:collection
          reason: "dart:collection should not be used"
          # Uses Glob notation, test using https://www.digitalocean.com/community/tools/glob
          includes:
            - "**/domain/**.dart"
          excludes:
            - "**.ex.dart"
        - source: package:external_source/banned_library.dart
          reason: "package:external_source/banned_library.dart should not be used anymore"
          includes:
            - "**/domain/**.dart"
          excludes:
            - "**.ex.dart"
