analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - cyclomatic_complexity:
      max_complexity: 4
      exclude:
        - class_name: Exclude
          method_name: excludeMethod
        - method_name: excludeMethod      
    - number_of_parameters:
      max_parameters: 2
      exclude:
        - class_name: Exclude
          method_name: avoidNumberOfParameters
        - method_name: avoidNumberOfParameters
    - function_lines_of_code:
      max_lines: 50
    - avoid_non_null_assertion
    - avoid_late_keyword:
      allow_initialized: true
    - avoid_global_state
    - avoid_returning_widgets:
      exclude:
        - class_name: ExcludeWidget 
          method_name: excludeWidgetMethod
        - method_name: excludeMethod
    - avoid_unnecessary_setstate
    - double_literal_format
    - avoid_unnecessary_type_assertions
    - avoid_unnecessary_type_casts
    - avoid_unrelated_type_assertions
    - avoid_unused_parameters:
      exclude:
        - class_name: Exclude 
          method_name: excludeMethod
        - method_name: excludeMethod
        - simpleMethodName
        - SimpleClassName
        - exclude
    - newline_before_return
    - no_empty_block:
      exclude:
        - class_name: Exclude 
          method_name: excludeMethod
        - method_name: excludeMethod
    - no_equal_then_else
    - avoid_debug_print_in_release
    - prefer_early_return
    - member_ordering:
      alphabetize: true
      order:
        - public_fields
        - private_fields
        - constructors
        - getters
        - setters
        - public_methods
        - private_methods
        - close_method
      widgets_order:
        - const_fields
        - static_fields
        - static_methods
        - public_fields
        - private_fields
        - public_methods
        - private_methods
        - constructors
        - build_method
        - init_state_method
        - did_change_dependencies_method
        - did_update_widget_method
        - dispose_method
    - no_magic_number
    - prefer_conditional_expressions
    - prefer_first
    - prefer_last
    - prefer_match_file_name
    - proper_super_calls
    - avoid_final_with_getter
