analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - cyclomatic_complexity:
      max_complexity: 4
    - number_of_parameters:
      max_parameters: 2
    - function_lines_of_code:
      max_lines: 50
    - avoid_non_null_assertion
    - avoid_late_keyword:
      allow_initialized: true
      ignored_types:
        - ColorTween
        - AnimationController
    - avoid_global_state
    - avoid_returning_widgets
    - avoid_unnecessary_setstate
    - double_literal_format
    - avoid_unnecessary_type_assertions
    - avoid_unnecessary_type_casts
    - avoid_unrelated_type_assertions
    - avoid_unused_parameters
    - newline_before_return
    - no_empty_block
    - no_equal_then_else
    - avoid_debug_print
    - prefer_guard_clause
    - member_ordering:
      alphabetize: true
      order:
        - public_fields
        - private_fields
        - constructors
        - getters
        - setters
        - public_methods
        - private_methods
        - close_method
      widgets_order:
        - const_fields
        - static_fields
        - static_methods
        - public_fields
        - private_fields
        - public_methods
        - private_methods
        - constructors
        - build_method
        - init_state_method
        - did_change_dependencies_method
        - did_update_widget_method
        - dispose_method
    - no_magic_number
    - prefer_conditional_expressions
    - prefer_first
    - prefer_last
    - prefer_match_file_name
    - proper_super_calls
