name: solid_lints_test
description: Test project for solid_lints rules
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  solid_lints:
    path: ../
  analyzer_testing: ^0.1.9
  test_reflective_loader: ^0.3.0
  test: ^1.25.0
