name: solid_lints_test
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  custom_lint: ^0.7.5

dev_dependencies:
  solid_lints:
    path: ../
  test: ^1.20.1
