name: no_magic_number_allowed_in_widget_params_test
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  solid_lints:
    path: ../../
  test: ^1.20.1
