analyzer:
  plugins:
    - ../custom_lint

custom_lint:
  rules:
    - banned_external_code:
      severity: warning
      entries:
        - class_name: BannedCodeUsage
          reason: "BannedCodeUsage is not allowed"
        - class_name: UnmodifiableListView
          reason: "UnmodifiableListView is not allowed"
