analyzer:
  plugins:
    - ../../custom_lint

custom_lint:
  rules:
    - banned_external_code:
      severity: warning
      entries:
        - class_name: BannedCodeUsage
          id: test
          reason: "BannedCodeUsage.test is not allowed"
