analyzer:
  plugins:
    - ../custom_lint

custom_lint:
  banned_external_code:
    severity: warning
    entries:
      - class_name: BannedCodeUsage
        id: test
        reason: "BannedCodeUsage.test is not allowed"
