analyzer:
  plugins:
    - ../../custom_lint

custom_lint:
  rules:
    - avoid_using_api:
      severity: warning
      entries:
        - class_name: BannedCodeUsage
          source: package:external_source
          reason: "BannedCodeUsage from package:external_source is not allowed"
        - class_name: UnmodifiableListView
          source: dart:collection
          reason: "UnmodifiableListView from dart:collection is not allowed"
