analyzer:
  plugins:
    - ../custom_lint

custom_lint:
  rules:
    - function_lines_of_code:
      max_lines: 5
      exclude:
        - class_name: ClassWithLongMethods
          method_name: longMethodExcluded
        - method_name: longFunctionExcluded     
        - longFunctionExcludedByDeclarationName
        - longMethodExcludedByDeclarationName
