name: Test deployment

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: ./doc/docusaurus

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./doc/docusaurus/package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Test build website
        run: npm run build
